export { useLegalRequests, useLegalRequest, LEGAL_REQUESTS_KEY, LEGAL_REQUEST_KEY, LEGAL_REQUEST_EVENTS_KEY } from './useLegalRequests';
export { useLegalComments, useLegalRequestEvents, LEGAL_COMMENTS_KEY } from './useLegalComments';
export { useLegalDocuments, useLegalDocument, useLegalDocumentSearch, LEGAL_TEMPLATES_KEY, LEGAL_TEMPLATE_KEY, LEGAL_VERSIONS_KEY } from './useLegalDocuments';
export type { LegalTemplateRow, LegalVersionRow, CreateTemplateArgs, DocumentSearchHit } from './useLegalDocuments';
export { useDocumentVersions } from './useDocumentVersions';
export { useFormSubmissions, LEGAL_SUBMISSIONS_KEY } from './useFormSubmissions';
export type { LegalSubmissionRow } from './useFormSubmissions';
export { useLegalPeople, useLegalTeam, useLegalVessels, useLegalIncidents, useLegalAlertSweep } from './useLegalLookups';
export type { LegalPerson, LegalTeamMember, LegalVessel, LegalIncident } from './useLegalLookups';
export { useLegalAttachments, getLegalAttachmentUrl, openLegalAttachment } from './useLegalAttachments';
